# Generated by Django 2.1.8 on 2020-08-11 12:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyusername',
            name='user',
            field=models.ForeignKey(null=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=django.contrib.auth.models.AnonymousUser,
        ),
    ]
